//
//  Phototext.swift
//  MySampleApp
//
//
// Copyright 2019 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

class Phototext: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    // have to include objectc support
    @objc var _userId: String?
    @objc var _noteId: String?
    
    class func dynamoDBTableName() -> String {

        return "schooled-mobilehub-969166170-Phototext"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_noteId" : "noteId",
        ]
    }
}
